package by.citech.handsfree.connection.fsm;

public enum EConnectionReport {
    UnconditionalTransition,
    BtLeNotSupported,
    BtNotSupported,
    BtPrepared,
    BtSearching,
    BtFound,
    BtConnecting,
    BtDisconnected,
//  BtNotificationStarted,
    BtConnectedCompatible,
    BtConnectedIncompatible,
//  PrepareBtStarted,
//  PrepareBtStopped,
    ConnectStarted,
    ConnectStopped,
    SearchStarted,
    SearchStopped,
//  NotificationStarted,
//  NotificationStopped,
    ChosenDevicePassedTheCheck,
    ChosenDeviceFailedTheCheck,
    GettingStatusStarted,
    GettingStatusStopped,
    GotStatus,
    GettingInitDataStarted,
    GettingInitDataStopped,
    GotInitData,
    TurningOff,
    TurningOn,
}
